fullnameOverride: "quantierra-gha-controller"
labels:
  stack: github-runners

certManagerEnabled: false

authSecret:
  enabled: true
  create: false
  name: gha-controller-manager

githubWebhookServer:
  enabled: false

metrics:
  serviceMonitor:
    enable: false

image:
  repository: summerwind/actions-runner-controller
  actionsRunnerRepositoryAndTag: ghcr.io/actions/actions-runner:v2.329.0
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: gha-controller

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
