apiVersion: v1
kind: Namespace
metadata:
  name: github-runners
  labels:
    workload: github-runners
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gha-runner-quota
  namespace: github-runners
spec:
  hard:
    pods: "100"
    requests.cpu: "40"
    requests.memory: 80Gi
    limits.cpu: "200"
    limits.memory: 400Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: gha-runner-limits
  namespace: github-runners
spec:
  limits:
    - type: Container
      default:
        cpu: "4"
        memory: 8Gi
      defaultRequest:
        cpu: "500m"
        memory: 1Gi
