githubConfigUrl: "https://github.com/quantierra"
githubConfigSecret:
  github_token: "REDACTED"

runnerGroup: "quantierra-gha"

minRunners: 2
maxRunners: 2

runnerScaleSetName: "selfhost-xl"

template:
  spec:
    nodeSelector:
      gha-tier: selfhost-l
    containers:
      - name: runner
        image: ghcr.io/jamesbrink/github-runner-full:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: RUNNER_LABELS
            value: "selfhosted-xl,selfhost-xl"
        resources:
          requests:
            cpu: "8"
            memory: "16Gi"
          limits:
            cpu: "32"
            memory: "64Gi"

containerMode:
  type: "dind"
